<a href="https://colab.research.google.com/github/dharvik-jalakam/exploratory-data-analysis/blob/main/EDALAB3_BDS0327.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df1web = pd.DataFrame({
    'CustomerID': [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 32, 34],
    'OrderValue': [278, 101, 613, 551, 507, 335, 259, 1166, 228, 914, 115, 111, 241, 497, 526]
})

df2web = pd.DataFrame({
    'CustomerID': [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 31, 33, 35],
    'OrderValue': [1084, 104, 1199, 457, 1166, 909, 501, 969, 619, 63, 376, 915, 746, 619, 368]
})

df1App = pd.DataFrame({
    'CustomerID': [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
    'OrderValue': [130, 410, 192, 72, 67, 214, 69, 203, 453, 196, 329, 155, 433, 42, 393]
})

df2App = pd.DataFrame({
    'CustomerID': [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
    'OrderValue': [255, 294, 83, 492, 213, 60, 302, 170, 444, 341, 336, 473, 461, 205, 315]
})

In [3]:
dfweb = pd.concat([df1web, df2web], ignore_index=True)
dfApp = pd.concat([df1App, df2App], ignore_index=True)

df = pd.concat([dfApp, dfweb], axis=1)
df

    CustomerID  OrderValue  CustomerID  OrderValue
0           11         130           1         278
1           12         410           3         101
2           13         192           5         613
3           14          72           7         551
4           15          67           9         507
5           16         214          11         335
6           17          69          13         259
7           18         203          15        1166
8           19         453          17         228
9           20         196          19         914
10          21         329          21         115
11          22         155          23         111
12          23         433          25         241
13          24          42          32         497
14          25         393          34         526
15          26         255           2        1084
16          27         294           4         104
17          28          83           6        1199
18          29         492           8         457
19          30         213          10        1166
20          31          60          12         909
21          32         302          14         501
22          33         170          16         969
23          34         444          18         619
24          35         341          20          63
25          36         336          22         376
26          37         473          24         915
27          38         461          31         746
28          39         205          33         619
29          40         315          35         368

In [5]:
dfweb = pd.concat([df1web, df2web], ignore_index=True)
dfApp = pd.concat([df1App, df2App], ignore_index=True)

df = dfweb.merge(dfApp, how='inner',on='CustomerID')
df

    CustomerID  OrderValue_x  OrderValue_y
0           11           335           130
1           13           259           192
2           15          1166            67
3           17           228            69
4           19           914           453
5           21           115           329
6           23           111           433
7           25           241           393
8           32           497           302
9           34           526           444
10          12           909           410
11          14           501            72
12          16           969           214
13          18           619           203
14          20            63           196
15          22           376           155
16          24           915            42
17          31           746            60
18          33           619           170
19          35           368           341

In [6]:
dfweb = pd.concat([df1web, df2web], ignore_index=True)
dfML = pd.concat([df1App, df2App], ignore_index=True)

df = dfweb.merge(dfApp, how='left')
df

    CustomerID  OrderValue
0            1         278
1            3         101
2            5         613
3            7         551
4            9         507
5           11         335
6           13         259
7           15        1166
8           17         228
9           19         914
10          21         115
11          23         111
12          25         241
13          32         497
14          34         526
15           2        1084
16           4         104
17           6        1199
18           8         457
19          10        1166
20          12         909
21          14         501
22          16         969
23          18         619
24          20          63
25          22         376
26          24         915
27          31         746
28          33         619
29          35         368

In [7]:
dfweb = pd.concat([df1web, df2web], ignore_index=True)
dfApp = pd.concat([df1App, df2App], ignore_index=True)

df = dfweb.merge(dfApp, how='right')
df

    CustomerID  OrderValue
0           11         130
1           12         410
2           13         192
3           14          72
4           15          67
5           16         214
6           17          69
7           18         203
8           19         453
9           20         196
10          21         329
11          22         155
12          23         433
13          24          42
14          25         393
15          26         255
16          27         294
17          28          83
18          29         492
19          30         213
20          31          60
21          32         302
22          33         170
23          34         444
24          35         341
25          36         336
26          37         473
27          38         461
28          39         205
29          40         315